-- CreateTable
CREATE TABLE "Pages" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING,
    "content" JSONB,
    "disabled" BOOL,
    "created_on" STRING,
    "last_updated_on" STRING,

    CONSTRAINT "Pages_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Pages_name_key" ON "Pages"("name");
