import Head from "next/head";
import Addpagesmain from "../components/pages/addpage";

export default function addpackage() {
  return (
    <div className="md:container m-auto px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Addpagesmain />
    </div>
  );
}
