import Head from "next/head";
import Imageupload from "../components/image/imageupload";

export default function Images() {
  return (
    <div className="md:container m-auto px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Imageupload />
    </div>
  );
}
