import Head from "next/head";

import Link from "next/link";

export default function Home() {
  return (
    <div className="container m-auto px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
      <h1 className="text-3xl font-bold text-center py-10">
        Telhealth Content Control Panel
      </h1>
      <div className=" grid grid-cols-2 gap-4 md:grid-cols-4  ">
        {[
          ["Add Package", "/addpackage"],
          ["Edit Package", "/addpackage"],
          ["Edit Package", "/addpackage"],
          ["Edit Package", "/addpackage"],
        ].map(([title, url]) => {
          return (
            <Link href={url} key={title}>
              <div className="transition duration-150 ease-in-out transform motion-safe:hover:scale-110  bg-white p-5 py-10 text-black text-center font-medium hover:bg-black hover:text-white hover:shadow border-double border-4 border-black hover:border-white ">
                {title}
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
Home.getLayout = function getLayout(page) {
  return page;
};
