import React,{createContext} from "react"
export const Tokencontext=createContext({address_1: null,
    address_2: null,
    affiliated_office: null,
    city: null,
    date_of_birth: null,
    email: null,
    first_name: null,
    gender: null,
    id: null,
    is_active: null,
    language: null,
    last_login: null,
    last_name: null,
    middle_name: null,
    mode: null,
    phone_number: null,
    state: null,
    
    zip: null})